<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Element119\AdminIndexerReport\Model\IndexerInfo;
use Element119\AdminIndexerReport\ViewModel\IndexerReport;
use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var IndexerReport $indexerReportViewModel */
$indexerReportViewModel = $block->getData('indexer_report_view_model');

/** @var IndexerInfo $indexerInfo */
$indexerInfo = $indexerReportViewModel->getIndexerInfo();
?>
<?php if (!$indexerInfo->isIndexerApplicationLockEnabled()): ?>
    <div class="indexer-notice warning">
        <?= $escaper->escapeHtml(__('Consider enabling the application lock mode for indexers to help them attempt to recover after experiencing a failure and provide developers with a more accurate status of the indexer in those failed states.')); ?>
        <br>
        <a href="https://developer.adobe.com/commerce/php/development/components/indexing/#using-application-lock-mode-for-reindex-processes"
           target="_blank">
            <?= $escaper->escapeHtml(__('See the relevant documentation for more information.')); ?>
        </a>
    </div>
<?php endif; ?>
