<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<?php if ($childHtml = trim($block->getChildHtml(''))): ?>
    <section id="indexer-notices-wrapper">
        <?= /** @noEscape */ $childHtml; ?>
    </section>
<?php endif; ?>
