<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<?php if ($indexerCronGrid = $block->getChildHtml('indexer-cron-grid')): ?>
    <section id="indexer-cron-grid-section">
        <h2 class="indexer-header">
            <?= $escaper->escapeHtml(__('Indexer Cron Report')); ?>
        </h2>

        <?= /** @noEscape */ $indexerCronGrid; ?>
    </section>
<?php endif; ?>
